const express =  require("express");
const cors =  require("cors");
const suppliers =  require("./api/suppliers.route.js");
const path =  require("path");
//const __dirname = path.resolve();
console.log(__dirname);
const app = express();
app.use(cors());
app.use(express.json());
//app.use(express.static(path.join(__dirname, '../frontend', 'build')));
app.use(function(req, res, next) {;
res.header("Access-Control-Allow-Origin", "*");
res.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
res.header("Access-Control-Allow-Headers", "x-access-token, Origin, X-Requested-With, Content-Type, Accept");
next();
});
app.use("/api/" , suppliers);
// app.get("*", (req, res) => {;
// res.sendFile(path.join(__dirname, "../frontend/build", "index.html"));
// });

module.exports = app;
